<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- needed this must have-->
    <PackageType>Template</PackageType>
    <PackageVersion>1.0.5.0</PackageVersion>
    <PackageId>Umlore.CleanArchitecture.Template</PackageId>
    <IsPackable>true</IsPackable>

    <Title>Template for clean architecture projects</Title>
    <Authors>Ivan Kiselev</Authors>    
    <PackageTags>dotnet-new;templates;cleanarchitecture;microservice</PackageTags>
    <TargetFramework>net9.0</TargetFramework>
    <RepositoryUrl>https://github.com/Iv-Umlore/ClearApiTemplatePackage</RepositoryUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageLicenseExpression>empty</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup> 

</Project>
