name: Publish Template

# Условия запуска
on:
  push:
    tags:
      - 'v*'  # Запуск при пуше тега, начинающегося с 'v' >> git push origin v1.0.0
  workflow_dispatch:  # Возможность ручного запуска из UI github


permissions:
  contents: read # Права на чтения РЕПО
  packages: write # Запись пакетов для дальнейшей публикации
 

# джоба с использованием Убунту
jobs:
  publish: 
    runs-on: ubuntu-latest
       
    # Шаги
    steps:
      # Копирования репо в рабочее пространство
      - name: Checkout repository
        uses: actions/checkout@v4 
    
      # Установка .Net пакета версии 9.х.х
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x.x'
    
      - name: Restore
        run: dotnet restore ././working/content/Template.csproj
    
      # Собираем пакет в Release-режиме
      - name: Pack
        # Так как csproj лежит не в основной дирестории репозитория - указываем путь
        run: |
            mkdir -p ./artifacts
            dotnet pack ././working/content/Template.csproj \
            --configuration Release \
            --no-restore \
            --output ./artifacts
    
      # Временный шаг, чтобы понять, куда собирается nuget пакет, чтобы после указать в nuget push
      - name: Debug artifacts
        run: find ./artifacts -name "*.nupkg"
    
      # Добавление источника для публикации
      # Публикация с использованием токена авторизации
      - name: Publish to Github Packages
        run: |
          dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push ./artifacts/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}
  
